theme: jekyll-theme-hacker
[*ATTACK ON TITAN*](https://wallpapers.com/images/high/scouting-legion-attack-on-titan-logo-hpy8im9jbawkbwqa.webp)
Among the violence and the confusion, Eren is the witness of how his mother is brutally eaten by a Titan during the attack. Full of anger and pain, the young boy swears revenge on the titans. In despair, poverty and orphanhood, Eren, Armin and Mikasa decide to join the army and fight for the humans.
